### ISSUE TITLE
Name and region of Istanbul chapter

### ISSUE THREAD

**Issue by aliok** [cncf/communitygroups#43]
![Screenshot 2023-09-08 at 00 34 42](https://github.com/cncf/communitygroups/assets/376732/1ed4027b-3b1e-4692-bbc9-66de1019ccd2)

When I check https://community.cncf.io/chapters/ and look for Istanbul chapter (https://community.cncf.io/istanbul/), I see 2 things that I think can be improved.

### 1. The name
The name "ISTANBUL, İSTANBUL" looks bad. Just showing "ISTANBUL" would be much better.
We don't have states in Turkey.

### 2. The region
City of Istanbul has 2 sides, one in Asia and one in Europe. However, Turkey is listed in Europe in many of the events / organizations / websites. For example, Ambassadors page lists Turkey in Europe: https://www.cncf.io/people/ambassadors/?_sft_lf-country=europe

Could you please change the region to Europe?

**Comment by aliok** [comment]
pinging other chapter organizers @halil-bugol @developer-guy @eminalemdar

**Comment by AudMonte01** [comment]
This is now updated
<img width="1312" alt="Screen Shot 2023-09-11 at 6 49 27 AM" src="https://github.com/cncf/communitygroups/assets/107572090/cc3b6b3f-01e0-4dd2-9d27-20b525343a63">

**Comment by AudMonte01** [comment]
I am going to close this issue, as this has been fixed.

**Comment by aliok** [comment]
@AudMonte01 
Thanks for the fixes.

I see the name in https://community.cncf.io/chapters/ --> Europe is still shown as `ISTANBUL, İSTANBUL`. Is it possible to simply write `ISTANBUL`?

**Comment by AudMonte01** [comment]
That is odd, because this is what I chose:

[image: Screen Shot 2023-09-12 at 10.40.21 AM.png]

Audra Montenegro
CNCF Community Program Manager
About Kubernetes Community Days <https://www.cncf.io/kcds/>
Host or join a local community group <https://community.cncf.io/>
US Time zone: Pacific

**Comment by aliok** [comment]
@AudMonte01 sorry the screenshot is not visible here on GitHub
